spring:
  docker:
    compose:
      enabled: false
  data:
    redis:
      # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      database: 0
      host: 127.0.0.1
      password: 123456
      port: 6379
      timeout: 3000ms # 连接超时时间（毫秒）
      # redis配置 Lettuce 是一个可伸缩线程安全的 Redis 客户端，多个线程可以共享同一个 RedisConnection，它利用优秀 netty NIO 框架来高效地管理多个连接
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1ms
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
logging:
  level:
    root: info